name: update_lists

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run searchfilter.sh
        run: sh ./searchfilter.sh
#      - name: switching from HTTPS to SSH
#        run: git remote set-url origin ${{ secrets.ssh }}
      - name: git ops
        run: |
          git status
          git config --global user.email "m_github@0x26.net"
          git config --global user.name "Masen Furer's action"
          git add .
          git commit -m "Auto update output filter lists"
          git push 
